### ISSUE TITLE
Semantic html start page

### ISSUE THREAD

**Issue by EphraimVC** [EphraimVC/chas-team8-webshop#2]
-  header 
- -main
- catalog container
- article for each product display
- footer

**Comment by Ahmed-ChasAcademy** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="main.css">
  <title>Webshop</title>
</head>
<body>
  <header>
    <h1>LOGO</h1>
    <button aria-label="View cart">CART</button>
  </header>
  <main>
    
    <section class="filters">
      <h2>Filter Products</h2>
      <form>
        <label for="sort-options">Sort Products:</label>
        <select name="sort-options" id="sort-options">
          <option value="price-asc">Sort by Price: Low to High</option>
          <option value="price-desc">Sort by Price: High to Low</option>
          <option value="rating">Sort by Rating</option>
        </select>
      </form>
    </section>

    
    <section class="categories">
      <h2>Categories</h2>
      <form>
        <label for="categories">Choose a Category:</label>
        <select name="categories" id="categories">
          <option value="mens-clothing">Men's Clothing</option>
          <option value="womens-clothing">Women's Clothing</option>
          <option value="jewelry">Jewelry</option>
          <option value="electronics">Electronics</option>
        </select>
      </form>
    </section>

    
    <section class="products">
      <h2>Products</h2>
      <article class="product">
        <img src="placeholder.jpg" alt="Product Image: Product title" />
        <h3>Product Title</h3>
        <p>Product Description</p>
        <p>Price: $XX.XX</p>
        <p>Rating: ★★★★☆</p>
        <button>Add to Cart</button>
      </article>

      <article class="product">
        <img src="placeholder.jpg" alt="Product Image: Product title" />
        <h3>Product Title</h3>
        <p>Product Description</p>
        <p>Price: $XX.XX</p>
        <p>Rating: ★★★☆☆</p>
        <button>Add to Cart</button>
      </article>
    </section>
  </main>
  <footer>

  </footer>
  <script src="/js/fetchData.js"></script>
</body>
</html>


basic semantic html

**Comment by Ahmed-V8** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="main.css">
  <title>Webshop</title>
</head>
<body>
  <header>
    <h1>LOGO</h1>
    <button aria-label="View cart">CART</button>
  </header>
  <main>
    
    <section class="filters">
      <h2>Filter Products</h2>
      <form>
        <label for="sort-options">Sort Products:</label>
        <select name="sort-options" id="sort-options">
          <option value="price-asc">Sort by Price: Low to High</option>
          <option value="price-desc">Sort by Price: High to Low</option>
          <option value="rating">Sort by Rating</option>
        </select>
      </form>
    </section>

    
    <section class="categories">
      <h2>Categories</h2>
      <form>
        <label for="categories">Choose a Category:</label>
        <select name="categories" id="categories">
          <option value="mens-clothing">Men's Clothing</option>
          <option value="womens-clothing">Women's Clothing</option>
          <option value="jewelry">Jewelry</option>
          <option value="electronics">Electronics</option>
        </select>
      </form>
    </section>

    
    <section class="products">
      <h2>Products</h2>
      <article class="product">
        <img src="placeholder.jpg" alt="Product Image: Product title" />
        <h3>Product Title</h3>
        <p>Product Description</p>
        <p>Price: $XX.XX</p>
        <p>Rating: ★★★★☆</p>
        <button>Add to Cart</button>
      </article>

      <article class="product">
        <img src="placeholder.jpg" alt="Product Image: Product title" />
        <h3>Product Title</h3>
        <p>Product Description</p>
        <p>Price: $XX.XX</p>
        <p>Rating: ★★★☆☆</p>
        <button>Add to Cart</button>
      </article>
    </section>
  </main>
  <footer>

  </footer>
  <script src="/js/fetchData.js"></script>
</body>
</html>
